server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BreakthrougBackEndTech/config-server
#          searchPaths: licensingservice,organizationservice
#          username: native-cloud-apps
#          password: 0ffended